### ISSUE TITLE
Tasks with inputs without URLs fail

### ISSUE THREAD

**Issue by Ayush5120** [elixir-europe/proTES#155]
The error is as follows:
`[2023-04-05 21:18:54,213: ERROR   ] Traceback (most recent call last):\n  File "/home/ayush/OSS/new/proTES/venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/home/ayush/OSS/new/proTES/venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File "/home/ayush/OSS/new/proTES/venv/lib/python3.10/site-packages/connexion/decorators/decorator.py", line 68, in wrapper\n    response = function(request)\n  File "/home/ayush/OSS/new/proTES/venv/lib/python3.10/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper\n    response = function(request)\n  File "/home/ayush/OSS/new/proTES/venv/lib/python3.10/site-packages/connexion/decorators/validation.py", line 193, in wrapper\n    response = function(request)\n  File "/home/ayush/OSS/new/proTES/venv/lib/python3.10/site-packages/connexion/decorators/parameter.py", line 116, in wrapper\n    return function(**kwargs)\n  File "/home/ayush/OSS/new/proTES/venv/lib/python3.10/site-packages/foca/utils/logging.py", line 61, in _wrapper\n    response = fn(*args, **kwargs)\n  File "/home/ayush/OSS/new/proTES/pro_tes/ga4gh/tes/server.py", line 45, in CreateTask\n    response = task_runs.create_task(request=request, **kwargs)\n  File "/home/ayush/OSS/new/proTES/pro_tes/ga4gh/tes/task_runs.py", line 175, in create_task\n    payload_marshalled.inputs = remove_auth(inputs)\n  File "/home/ayush/OSS/new/proTES/pro_tes/ga4gh/tes/task_runs.py", line 160, in remove_auth\n    return [remove_auth_from_url(item.url)\n  File "/home/ayush/OSS/new/proTES/pro_tes/ga4gh/tes/task_runs.py", line 162, in <listcomp>\n    if item.url is not None\nAttributeError: 'str' object has no attribute 'url' [foca.errors.exceptions]`

**Comment by uniqueg** [comment]
Introduced in 02681862d2c2427fc55c1208a2e678d04ee73f36
